<template><view class="page">
  <swiper class="announce" indicator-dots autoplay circular><swiper-item v-for="item in announcements" :key="item.title"><view class="ann"><image :src="item.image" mode="aspectFill"/><view class="ann-info"><text class="tag">{{item.tag}}</text><text class="ann-title">{{item.title}}</text><text class="ann-sub">{{item.sub}}</text></view></view></swiper-item></swiper>
  <view class="card overview"><view><text class="num orange">312</text><text class="label">累计卡路里 (kcal)</text></view><view class="divider"/><view><text class="num">4.50</text><text class="label">累计里程 (km)</text></view></view>
  <view class="section-title">勋章展馆</view><view class="card medal-hall" @tap="go('/pages/achievement/achievement')"><text class="intro">完赛线路即可铸造专属勋章 · 已收藏 1/3 枚</text><view class="medals"><view v-for="(r,i) in routes" :key="r.id"><image :class="{locked:i>0}" :src="r.medal" mode="aspectFit"/><text>{{r.spirit}}</text><text class="state">{{i===0?'已收藏':'未解锁'}}</text></view></view><view class="enter">进入勋章展馆，查看勋章价值 ›</view></view>
  <view class="section-title">推荐路跑线路</view><view class="route" v-for="r in routes" :key="r.id" @tap="go('/pages/route/route?id='+r.id)"><view class="route-head"><image :src="r.scene" mode="aspectFill"/><view class="mask"/><view class="route-top"><text>{{r.name}}</text><text class="spirit">{{r.spirit}}</text></view><text class="path">{{r.from}} 至 {{r.to}} · 全程 {{r.total}}km</text></view><view class="route-body"><text class="desc">{{r.desc}}</text><view class="progress"><view :style="{width:r.pct+'%',background:r.theme}"/></view><view class="foot"><text>已跑 {{r.distance}}km · 抵达 {{r.current}}</text><text class="orange">{{r.pct}}%</text></view></view></view>
  <view class="tip">选择一条线路，开始你的虚拟远征</view>
</view></template>
<script>import {routes,announcements} from '../../common/mock.js'; export default{data:()=>({routes,announcements}),methods:{go(url){uni.navigateTo({url})}}}</script>
<style scoped>
.page{padding-bottom:30rpx}.announce{height:320rpx;margin:24rpx;border-radius:20rpx;overflow:hidden}.ann,.ann image{width:100%;height:100%;position:relative}.ann-info{position:absolute;left:30rpx;right:30rpx;bottom:42rpx;color:#fff;text-shadow:0 2rpx 8rpx #333}.tag{display:inline-block;background:rgba(255,106,0,.92);border-radius:8rpx;padding:4rpx 16rpx;font-size:22rpx}.ann-title,.ann-sub{display:block}.ann-title{font-size:36rpx;font-weight:700;margin-top:10rpx}.ann-sub{font-size:25rpx;margin-top:6rpx}.overview{display:flex;align-items:center;text-align:center}.overview>view{flex:1}.num{display:block;font-size:52rpx;font-weight:700}.orange{color:#ff6a00}.label{display:block;color:#999;font-size:24rpx;margin-top:8rpx}.overview .divider{flex:0 0 1rpx;height:70rpx;background:#eee}.intro{font-size:24rpx;color:#999}.medals{display:flex;justify-content:space-around;margin-top:16rpx}.medals view{display:flex;flex:1;align-items:center;flex-direction:column}.medals image{width:140rpx;height:140rpx}.medals .locked{filter:grayscale(1);opacity:.4}.medals text{font-size:25rpx;font-weight:600}.medals .state{font-size:21rpx;color:#ff6a00;margin-top:4rpx}.enter{text-align:center;color:#ff6a00;border-top:1rpx solid #eee;padding-top:18rpx;margin-top:20rpx}.route{margin:20rpx 24rpx;background:#fff;border-radius:20rpx;overflow:hidden;box-shadow:0 4rpx 16rpx rgba(0,0,0,.06)}.route-head{height:240rpx;position:relative}.route-head>image,.mask{position:absolute;width:100%;height:100%}.mask{background:linear-gradient(180deg,rgba(0,0,0,.1),rgba(0,0,0,.65))}.route-top{position:absolute;left:30rpx;right:30rpx;top:26rpx;display:flex;justify-content:space-between;color:white;font-size:44rpx;font-weight:700}.spirit{font-size:26rpx;border:2rpx solid rgba(255,255,255,.8);border-radius:99rpx;padding:4rpx 20rpx}.path{position:absolute;left:30rpx;bottom:22rpx;color:white;font-size:25rpx}.route-body{padding:24rpx 30rpx}.desc{display:block;color:#999;font-size:24rpx;line-height:1.5;margin-bottom:20rpx}.progress{height:14rpx;background:#eee;border-radius:99rpx;overflow:hidden}.progress view{height:100%;border-radius:99rpx}.foot{display:flex;justify-content:space-between;color:#999;font-size:24rpx;margin-top:14rpx}.tip{text-align:center;color:#bbb;font-size:24rpx;margin:30rpx}
</style>
